server:
  port: 8081
spring:
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
    port: 587
    username: 2360187899@qq.com
    password: eafneqgwbbeeeadj
mybatis-plus:
  mapper-locations: classpath*:com/dawn/dawn/**/xml/*.xml
  globalConfig:
    dbConfig:
      logicDeleteField: deleted
      logicDeleteValue: 1
      logicNotDeleteValue: 0
  configuration:
    mapUnderscoreToCamelCase: true
    cacheEnabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl