spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dawn
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  rabbitmq:
    host: 120.27.215.0
    port: 5672
    username: mytest
    password: test123
    listener:
      simple:
        acknowledge-mode: manual
    template:
      mandatory: true
    publisher-returns: true
    publisher-confirm-type: correlated
    connection-timeout: 3600
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liT1TPjwEDKfRrOO
            client-secret: 0b16bb9973f5cb973a658e543474e696991d6e90
ip:
  xdbPath: D:\project\project\dawn\src\main\resources\static\ip\csdn-ip2region.xdb
upload:
  path: E:/path/file/
  chunk: E:/path/chunk/
file:
  url: http://localhost
  path: /files